######################################################################
# Automatically generated by qmake (3.0) ? 8 9 02:38:02 2013
######################################################################

QT += opengl

TEMPLATE = app
TARGET = qt5shader
INCLUDEPATH += .

# Input
HEADERS += openglwindow.h
SOURCES += main.cpp openglwindow.cpp
